import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the robotics modules
  roboticsSidebar: [
    {
      type: 'category',
      label: 'Module 1 - Robotic Nervous System (ROS 2)',
      items: [
        'modules/module-1/index',
        'modules/module-1/lessons/intro',
        'modules/module-1/lessons/ros2-nodes',
        'modules/module-1/lessons/topics-services',
        'modules/module-1/lessons/urdf',
        'modules/module-1/lessons/exercises'
      ],
      link: {
        type: 'doc',
        id: 'modules/module-1/index'
      }
    },
    {
      type: 'category',
      label: 'Module 2 - Digital Twin (Gazebo & Unity)',
      items: [
        'modules/module-2/index',
        'modules/module-2/lessons/intro',
        'modules/module-2/lessons/physics-simulation',
        'modules/module-2/lessons/gazebo-environment',
        'modules/module-2/lessons/unity-rendering',
        'modules/module-2/lessons/sensors',
        'modules/module-2/lessons/integration',
        'modules/module-2/lessons/debugging',
        'modules/module-2/lessons/exercises',
        'modules/module-2/lessons/final-project'
      ],
      link: {
        type: 'doc',
        id: 'modules/module-2/index'
      }
    },
    // Additional modules will be added here as they are created
  ]
};

export default sidebars;
